export type LandType =
  | "public"
  | "blm"
  | "forest_service"
  | "state_park"
  | "fee"
  | "protected"
  | "private";

export type Hotspot = {
  id: string;
  name: string;
  lat: number;
  lng: number;
  state: string;
  land: LandType;
  minerals: string[];
  difficulty: "easy" | "moderate" | "hard";
  trust: number;
  rules: string;
  description: string;
  note: string;
};

export const LAND_LABEL: Record<LandType, string> = {
  public: "public",
  blm: "BLM",
  forest_service: "USFS",
  state_park: "state park",
  fee: "pay-to-dig",
  protected: "observe only",
  private: "private",
};

export const HOTSPOTS: Hotspot[] = [
  {
    id: "duluth-park-point",
    name: "Park Point Beach",
    lat: 46.7725,
    lng: -92.0833,
    state: "MN",
    land: "public",
    minerals: ["ls-agate", "jasper", "epidote"],
    difficulty: "easy",
    trust: 0.98,
    rules: "City beach. Surface hand-collecting. No mechanical digging.",
    description: "Seven-mile spit. Agates concentrate on the swash after northeasters turn the gravel.",
    note: "Paved parking, restrooms, playground at the beach house.",
  },
  {
    id: "beaver-bay",
    name: "Beaver Bay Shingle Beach",
    lat: 47.2575,
    lng: -91.2986,
    state: "MN",
    land: "public",
    minerals: ["ls-agate", "prehnite", "thomsonite"],
    difficulty: "easy",
    trust: 0.99,
    rules: "Public North Shore access. Hand-collect pebbles along the shoreline.",
    description: "Keweenawan basalts shedding banded agate and zeolites onto a rocky beach.",
    note: "Water shoes. Smooth skippers everywhere.",
  },
  {
    id: "petoskey",
    name: "Petoskey State Park",
    lat: 45.4056,
    lng: -84.9125,
    state: "MI",
    land: "state_park",
    minerals: ["petoskey", "calcite"],
    difficulty: "easy",
    trust: 0.99,
    rules: "Michigan 25 lb / person / year. Surface gathering only.",
    description: "Devonian Hexagonaria in the surf. Pattern appears when wet.",
    note: "Dunes, pavilions, swimming. Wet the stone.",
  },
  {
    id: "crisp-point",
    name: "Crisp Point Light Beach",
    lat: 46.7533,
    lng: -85.2581,
    state: "MI",
    land: "public",
    minerals: ["yooperlite", "ls-agate", "jasper"],
    difficulty: "moderate",
    trust: 0.97,
    rules: "Public beach. 365 nm UV for night hunting.",
    description: "Remote Superior shore. Sodalite syenite pebbles burn orange under longwave UV.",
    note: "UV glasses, warm layers. Night hunt is the point.",
  },
  {
    id: "keweenaw",
    name: "Keweenaw Copper Country",
    lat: 47.2472,
    lng: -88.4534,
    state: "MI",
    land: "public",
    minerals: ["copper", "prehnite", "datolite"],
    difficulty: "moderate",
    trust: 0.96,
    rules: "Respect posted private and park land. Shoreline float copper is the ethical target.",
    description: "Native copper in amygdaloidal basalt. The type landscape for hackly float copper.",
    note: "Heft is the tell. Check local club trips.",
  },
  {
    id: "keokuk",
    name: "Keokuk Geode Beds",
    lat: 40.4042,
    lng: -91.3855,
    state: "IA",
    land: "public",
    minerals: ["quartz", "calcite", "pyrite", "chalcedony"],
    difficulty: "moderate",
    trust: 0.96,
    rules: "Creek gravel bars and pay quarries. Confirm landowner lines.",
    description: "Mississippian Warsaw Formation geodes — quartz, calcite scalenohedra, pyrite.",
    note: "Goggles and a crack hammer. Kids remember the first open geode.",
  },
  {
    id: "hamilton-il",
    name: "Hamilton Geode Mine",
    lat: 40.396,
    lng: -91.339,
    state: "IL",
    land: "fee",
    minerals: ["quartz", "calcite", "chalcedony"],
    difficulty: "easy",
    trust: 0.97,
    rules: "Pay-to-dig. Keep what you open. Staffed.",
    description: "Same Warsaw beds as Keokuk, on the Illinois side of the river.",
    note: "Closest classic geode stop to the central Illinois river towns.",
  },
  {
    id: "mazon-creek",
    name: "Mazon Creek",
    lat: 41.271,
    lng: -88.396,
    state: "IL",
    land: "public",
    minerals: ["siderite nodules", "carboniferous fossils"],
    difficulty: "moderate",
    trust: 0.95,
    rules: "Pit 11 and spoil piles. Respect posted property. Fossils, not minerals, are the prize.",
    description: "Ironstone nodules with Carboniferous plants and the Tully monster. Midwest legend.",
    note: "Split nodules after freeze-thaw. Field club guidance recommended.",
  },
  {
    id: "cave-in-rock",
    name: "Illinois-Kentucky Fluorspar District",
    lat: 37.47,
    lng: -88.166,
    state: "IL",
    land: "private",
    minerals: ["fluorite", "calcite", "barite", "galena"],
    difficulty: "hard",
    trust: 0.9,
    rules: "Historic district. Most mines closed. No trespass. Club trips and remaining fee sites only.",
    description: "Once the nation's fluorite capital. Octahedral purple-yellow fluorite is the heritage stone of Illinois.",
    note: "Treat as heritage / observe unless a listed fee dig is open.",
  },
  {
    id: "herkimer",
    name: "Herkimer Diamond Mines",
    lat: 43.1417,
    lng: -74.9669,
    state: "NY",
    land: "fee",
    minerals: ["herkimer", "dolomite", "calcite"],
    difficulty: "easy",
    trust: 0.99,
    rules: "Commercial pay-to-dig. You keep what you find.",
    description: "Doubly terminated quartz in Cambrian Little Falls dolostone.",
    note: "Sluice tables for kids. Museum on site.",
  },
  {
    id: "franklin-nj",
    name: "Franklin / Sterling Hill",
    lat: 41.122,
    lng: -74.59,
    state: "NJ",
    land: "fee",
    minerals: ["willemite", "franklinite", "calcite"],
    difficulty: "easy",
    trust: 0.99,
    rules: "Museum collecting dumps. UV fluorescent night hunts on scheduled dates.",
    description: "The fluorescent capital of the world. Willemite-calcite burns green-red under shortwave.",
    note: "Bring SW UV. Museum is the access, not the historic workings.",
  },
  {
    id: "st-clair",
    name: "St. Clair Fern Beds",
    lat: 40.7189,
    lng: -76.1953,
    state: "PA",
    land: "public",
    minerals: ["pyrophyllite ferns", "anthracite"],
    difficulty: "moderate",
    trust: 0.95,
    rules: "Abandoned strip-mine tailings. Boots and glasses.",
    description: "Pennsylvanian shale splits to white pyrophyllite ferns on black.",
    note: "A butter knife splits many pieces. Spectacular for kids.",
  },
  {
    id: "crater-diamonds",
    name: "Crater of Diamonds State Park",
    lat: 34.0333,
    lng: -93.6706,
    state: "AR",
    land: "state_park",
    minerals: ["diamond", "amethyst", "garnet", "jasper"],
    difficulty: "easy",
    trust: 0.99,
    rules: "Park fee. 37-acre plowed lamproite. You keep certified diamonds.",
    description: "The only public diamond pipe on Earth where visitors keep what they find.",
    note: "Park lab will certify. After rain is best.",
  },
  {
    id: "mt-ida",
    name: "Mount Ida Quartz Belt",
    lat: 34.556,
    lng: -93.634,
    state: "AR",
    land: "fee",
    minerals: ["quartz", "smoky-quartz"],
    difficulty: "easy",
    trust: 0.98,
    rules: "Pay mines along the belt. Keep crystals. Hand tools.",
    description: "Ouachita vein quartz — clear points by the bucket from decomposed veins.",
    note: "Family mines with washing tables.",
  },
  {
    id: "magnet-cove",
    name: "Magnet Cove",
    lat: 34.452,
    lng: -92.868,
    state: "AR",
    land: "private",
    minerals: ["magnetite", "rutile", "pyrite"],
    difficulty: "hard",
    trust: 0.88,
    rules: "Most land private. Club access only. Famous mineralogy, not a walk-up.",
    description: "Alkaline complex, type locality density. Magnetite, rutile, unusual silicates.",
    note: "Go with a club. Do not wander fences.",
  },
  {
    id: "emerald-hollow",
    name: "Emerald Hollow Mine",
    lat: 35.9189,
    lng: -81.0808,
    state: "NC",
    land: "fee",
    minerals: ["emerald", "hiddenite", "aquamarine", "garnet"],
    difficulty: "easy",
    trust: 0.98,
    rules: "Pay-to-prospect. Sluice, creek, and hillside.",
    description: "Only emerald mine in North America open to the public.",
    note: "Seated sluices. Staff ID tables.",
  },
  {
    id: "franklin-nc",
    name: "Franklin Cowee Valley",
    lat: 35.182,
    lng: -83.381,
    state: "NC",
    land: "fee",
    minerals: ["corundum", "garnet", "kyanite"],
    difficulty: "easy",
    trust: 0.97,
    rules: "Pay mines. You keep rubies and sapphires from the gravel.",
    description: "Cowee Valley corundum in weathered amphibolite. Bucket-and-flume classic.",
    note: "Bring a lunch. Red and blue hex barrels.",
  },
  {
    id: "graves-mountain",
    name: "Graves Mountain",
    lat: 33.7431,
    lng: -82.5186,
    state: "GA",
    land: "fee",
    minerals: ["rutile", "hematite", "kyanite"],
    difficulty: "moderate",
    trust: 0.97,
    rules: "Open on scheduled Rock Swap & Dig days. Check Georgia Mineral Society.",
    description: "World-class rutile and iridescent hematite.",
    note: "Hematite flashes like gasoline on water.",
  },
  {
    id: "morefield",
    name: "Morefield Mine",
    lat: 37.342,
    lng: -77.98,
    state: "VA",
    land: "fee",
    minerals: ["amazonite", "topaz", "cleavelandite"],
    difficulty: "easy",
    trust: 0.96,
    rules: "Pay-to-dig pegmatite. Seasonal.",
    description: "Amelia Courthouse pegmatite — amazonite and rare pegmatite minerals.",
    note: "Confirm seasonal hours before driving.",
  },
  {
    id: "topaz-mountain",
    name: "Topaz Mountain",
    lat: 39.7128,
    lng: -113.1039,
    state: "UT",
    land: "blm",
    minerals: ["topaz", "bixbyite", "red beryl"],
    difficulty: "moderate",
    trust: 0.98,
    rules: "Free BLM. Hand tools. No claims jumping.",
    description: "Rhyolite pockets of sherry topaz. Crystals weather into the washes.",
    note: "Kids spot crystals in sand. Sun, water, no shade.",
  },
  {
    id: "crystal-park",
    name: "Crystal Park",
    lat: 45.4975,
    lng: -113.0972,
    state: "MT",
    land: "forest_service",
    minerals: ["quartz", "smoky-quartz", "amethyst"],
    difficulty: "easy",
    trust: 0.99,
    rules: "USFS recreation area. Day-use fee. Trowels and screens.",
    description: "High decomposed granite packed with quartz prisms.",
    note: "Picnic tables, restrooms, alpine air.",
  },
  {
    id: "oregon-sunstone",
    name: "Oregon Sunstone Public Area",
    lat: 42.7214,
    lng: -119.8822,
    state: "OR",
    land: "blm",
    minerals: ["sunstone", "labradorite"],
    difficulty: "easy",
    trust: 0.99,
    rules: "Free BLM, ~4 sq mi reserved for hobby collecting.",
    description: "Copper-bearing labradorite in weathered basalt soil. Champagne to schiller.",
    note: "Surface crawling. Kids' eyes are closer to the ground.",
  },
  {
    id: "glass-buttes",
    name: "Glass Buttes",
    lat: 43.5594,
    lng: -120.0617,
    state: "OR",
    land: "blm",
    minerals: ["obsidian"],
    difficulty: "moderate",
    trust: 0.98,
    rules: "Free BLM. 250 lb / person / year. Gloves.",
    description: "Obsidian dome: rainbow, mahogany, lace, fire.",
    note: "Sharp. Leather gloves and eye protection.",
  },
  {
    id: "rockhound-sp",
    name: "Rockhound State Park",
    lat: 32.1869,
    lng: -107.6167,
    state: "NM",
    land: "state_park",
    minerals: ["thunderegg", "agate", "jasper"],
    difficulty: "easy",
    trust: 0.99,
    rules: "First US park created for collecting. 15 lb / person.",
    description: "Little Florida Mountains — thundereggs and chalcedony nodules.",
    note: "Campground, visitor center, marked trails.",
  },
  {
    id: "hauser-beds",
    name: "Hauser Geode Beds",
    lat: 33.56,
    lng: -114.98,
    state: "CA",
    land: "blm",
    minerals: ["thunderegg", "agate", "quartz"],
    difficulty: "moderate",
    trust: 0.94,
    rules: "BLM. Hand tools. Pack out. Summer heat is lethal.",
    description: "Chuckwalla Valley geodes in andesite. Classic Southern California winter hunt.",
    note: "Go November–March. Water, spare tire, tell someone.",
  },
  {
    id: "jade-cove",
    name: "Jade Cove",
    lat: 35.921,
    lng: -121.469,
    state: "CA",
    land: "public",
    minerals: ["nephrite"],
    difficulty: "moderate",
    trust: 0.93,
    rules: "Big Sur coast. Surface jade from the cobble. Respect closures and surf.",
    description: "Nephrite cobbles in the surf zone. Greasy, tough, heavy for size.",
    note: "Sneaker waves. Never turn your back on the Pacific.",
  },
  {
    id: "blanchard",
    name: "Blanchard Mine (Hansonburg)",
    lat: 33.75,
    lng: -106.37,
    state: "NM",
    land: "fee",
    minerals: ["fluorite", "galena", "barite", "quartz"],
    difficulty: "moderate",
    trust: 0.95,
    rules: "Claim / fee access. Check current caretaker. No blasting.",
    description: "Bingham, NM — blue-green fluorite with galena. Desert classic.",
    note: "Sun, rattlesnakes, high desert. Confirm access.",
  },
  {
    id: "sweetwater",
    name: "Sweetwater Mine District",
    lat: 37.94,
    lng: -90.82,
    state: "MO",
    land: "private",
    minerals: ["galena", "calcite", "sphalerite"],
    difficulty: "hard",
    trust: 0.9,
    rules: "Active/historic lead district. No trespass. Specimens move through dealers, not the dump.",
    description: "Viburnum Trend calcite-galena. Museum-grade scalenohedra. Not a hobby pit.",
    note: "Buy from reputable dealers. Do not enter workings.",
  },
  {
    id: "pikes-peak",
    name: "Pikes Peak Batholith",
    lat: 38.84,
    lng: -105.04,
    state: "CO",
    land: "forest_service",
    minerals: ["amazonite", "smoky-quartz", "topaz", "fluorite"],
    difficulty: "moderate",
    trust: 0.94,
    rules: "National forest. No collecting in park units. Stay off claims.",
    description: "Miarolitic granite: amazonite + smoky quartz the signature pair.",
    note: "Altitude, afternoon storms. Club trips beat wandering.",
  },
  {
    id: "mt-antero",
    name: "Mount Antero",
    lat: 38.674,
    lng: -106.246,
    state: "CO",
    land: "forest_service",
    minerals: ["aquamarine", "phenakite", "beryl"],
    difficulty: "hard",
    trust: 0.92,
    rules: "High alpine. Claims everywhere. Daylight, weather window, lungs.",
    description: "One of the highest gem localities in North America. Aquamarine in granite.",
    note: "14k-adjacent. This is mountaineering with a rock hammer.",
  },
  {
    id: "yellowstone",
    name: "Obsidian Cliff, Yellowstone",
    lat: 44.82,
    lng: -110.73,
    state: "WY",
    land: "protected",
    minerals: ["obsidian"],
    difficulty: "easy",
    trust: 1,
    rules: "National park. Collecting is illegal. Observe only.",
    description: "Type landscape for rhyolitic obsidian. Look, photograph, leave.",
    note: "Stewardship is the find.",
  },
  {
    id: "isle-royale",
    name: "Isle Royale Greenstone",
    lat: 48.0,
    lng: -88.83,
    state: "MI",
    land: "protected",
    minerals: ["chlorastrolite", "prehnite", "copper"],
    difficulty: "hard",
    trust: 1,
    rules: "National park. Collecting chlorastrolite is illegal here.",
    description: "Michigan state gem in situ. The ethical hunt is on other UP beaches with local rules.",
    note: "Observe. Do not pocket the park.",
  },
];

export const HOTSPOT_INDEX = new Map(HOTSPOTS.map((h) => [h.id, h]));
