export type Luster =
  | "metallic"
  | "submetallic"
  | "vitreous"
  | "resinous"
  | "pearly"
  | "silky"
  | "greasy"
  | "waxy"
  | "adamantine"
  | "dull"
  | "earthy";

export type System =
  | "cubic"
  | "tetragonal"
  | "hexagonal"
  | "trigonal"
  | "orthorhombic"
  | "monoclinic"
  | "triclinic"
  | "amorphous";

export type Rarity = "common" | "uncommon" | "rare" | "legendary";
export type Magnetism = "none" | "weak" | "strong";

export type Mineral = {
  id: string;
  name: string;
  formula: string;
  system: System;
  mohs: [number, number];
  sg: [number, number];
  streak: string;
  luster: Luster;
  diaphaneity: string;
  cleavage: string;
  magnetism: Magnetism;
  rarity: Rarity;
  group: string;
  colors: string[];
  hues: number[];
  sat: number;
  val: number;
  metallic: boolean;
  localities: string[];
  notes: string;
  tests: string;
  xp: number;
};

export const MINERALS: Mineral[] = [
  {
    id: "quartz",
    name: "Quartz",
    formula: "SiO₂",
    system: "trigonal",
    mohs: [7, 7],
    sg: [2.65, 2.65],
    streak: "white",
    luster: "vitreous",
    diaphaneity: "transparent to translucent",
    cleavage: "none · conchoidal fracture",
    magnetism: "none",
    rarity: "common",
    group: "tectosilicate",
    colors: ["colorless", "white", "smoky"],
    hues: [0, 40],
    sat: 0.08,
    val: 0.88,
    metallic: false,
    localities: ["Hot Springs AR", "Crystal Park MT", "Herkimer NY"],
    notes: "Most abundant mineral in the crust. Hexagonal prisms, no cleavage, scratches glass.",
    tests: "Mohs 7 · no streak color · conchoidal fracture",
    xp: 12,
  },
  {
    id: "amethyst",
    name: "Amethyst",
    formula: "SiO₂",
    system: "trigonal",
    mohs: [7, 7],
    sg: [2.65, 2.65],
    streak: "white",
    luster: "vitreous",
    diaphaneity: "transparent to translucent",
    cleavage: "none · conchoidal fracture",
    magnetism: "none",
    rarity: "uncommon",
    group: "tectosilicate",
    colors: ["violet", "purple"],
    hues: [270, 290],
    sat: 0.55,
    val: 0.62,
    metallic: false,
    localities: ["Four Peaks AZ", "Thunder Bay ON", "Rio Grande do Sul"],
    notes: "Fe³⁺ color centers in quartz. Companion stone of this instrument. Color often zones toward the rims of crystals.",
    tests: "Mohs 7 · white streak · hexagonal prism",
    xp: 28,
  },
  {
    id: "citrine",
    name: "Citrine",
    formula: "SiO₂",
    system: "trigonal",
    mohs: [7, 7],
    sg: [2.65, 2.65],
    streak: "white",
    luster: "vitreous",
    diaphaneity: "transparent",
    cleavage: "none",
    magnetism: "none",
    rarity: "uncommon",
    group: "tectosilicate",
    colors: ["yellow", "honey", "amber"],
    hues: [38, 52],
    sat: 0.62,
    val: 0.78,
    metallic: false,
    localities: ["Brazil", "Madagascar"],
    notes: "Natural citrine is scarce; much market material is heat-treated amethyst.",
    tests: "Mohs 7 · pale yellow body color, not metallic gold",
    xp: 22,
  },
  {
    id: "smoky-quartz",
    name: "Smoky Quartz",
    formula: "SiO₂",
    system: "trigonal",
    mohs: [7, 7],
    sg: [2.65, 2.65],
    streak: "white",
    luster: "vitreous",
    diaphaneity: "translucent",
    cleavage: "none",
    magnetism: "none",
    rarity: "common",
    group: "tectosilicate",
    colors: ["brown", "gray", "black"],
    hues: [25, 40],
    sat: 0.28,
    val: 0.32,
    metallic: false,
    localities: ["Pikes Peak CO", "Crystal Park MT"],
    notes: "Irradiation of Al-bearing quartz. Common in granite miarolitic cavities.",
    tests: "Mohs 7 · translucent brown, not tourmaline's striations",
    xp: 16,
  },
  {
    id: "rose-quartz",
    name: "Rose Quartz",
    formula: "SiO₂",
    system: "trigonal",
    mohs: [7, 7],
    sg: [2.65, 2.65],
    streak: "white",
    luster: "vitreous",
    diaphaneity: "translucent",
    cleavage: "none",
    magnetism: "none",
    rarity: "common",
    group: "tectosilicate",
    colors: ["pink"],
    hues: [330, 350],
    sat: 0.38,
    val: 0.78,
    metallic: false,
    localities: ["Black Hills SD", "Minas Gerais"],
    notes: "Massive, rarely euhedral. Color from dumortierite-like fibers / Ti-Fe.",
    tests: "Mohs 7 · massive pink, cloudy",
    xp: 14,
  },
  {
    id: "chalcedony",
    name: "Chalcedony",
    formula: "SiO₂",
    system: "trigonal",
    mohs: [6.5, 7],
    sg: [2.55, 2.64],
    streak: "white",
    luster: "waxy",
    diaphaneity: "translucent",
    cleavage: "none",
    magnetism: "none",
    rarity: "common",
    group: "tectosilicate",
    colors: ["gray", "blue", "white"],
    hues: [200, 220],
    sat: 0.18,
    val: 0.7,
    metallic: false,
    localities: ["Oregon", "Namibia"],
    notes: "Microcrystalline quartz. Waxy luster is the field tell versus crystalline quartz.",
    tests: "Waxy luster · conchoidal · Mohs ~7",
    xp: 12,
  },
  {
    id: "agate",
    name: "Agate",
    formula: "SiO₂",
    system: "trigonal",
    mohs: [6.5, 7],
    sg: [2.55, 2.64],
    streak: "white",
    luster: "waxy",
    diaphaneity: "translucent",
    cleavage: "none",
    magnetism: "none",
    rarity: "common",
    group: "tectosilicate",
    colors: ["banded", "red", "white", "gray"],
    hues: [10, 30, 200],
    sat: 0.35,
    val: 0.55,
    metallic: false,
    localities: ["Lake Superior", "Madras OR", "Botswana"],
    notes: "Concentric chalcedony banding from vesicle infill in volcanic host.",
    tests: "Banding under wet surface · waxy · Mohs 7",
    xp: 18,
  },
  {
    id: "ls-agate",
    name: "Lake Superior Agate",
    formula: "SiO₂",
    system: "trigonal",
    mohs: [6.5, 7],
    sg: [2.6, 2.64],
    streak: "white",
    luster: "waxy",
    diaphaneity: "translucent",
    cleavage: "none",
    magnetism: "none",
    rarity: "uncommon",
    group: "tectosilicate",
    colors: ["iron-red", "white", "orange"],
    hues: [8, 22],
    sat: 0.62,
    val: 0.48,
    metallic: false,
    localities: ["North Shore MN", "Wisconsin Point", "Michigan UP"],
    notes: "Keweenawan amygdaloidal basalt, iron-stained fortification banding. Minnesota state gem.",
    tests: "Iron-red fortification bands · water-worn · waxy",
    xp: 32,
  },
  {
    id: "jasper",
    name: "Jasper",
    formula: "SiO₂",
    system: "trigonal",
    mohs: [6.5, 7],
    sg: [2.5, 2.6],
    streak: "white",
    luster: "dull",
    diaphaneity: "opaque",
    cleavage: "none",
    magnetism: "none",
    rarity: "common",
    group: "tectosilicate",
    colors: ["red", "brown", "yellow", "green"],
    hues: [8, 35],
    sat: 0.55,
    val: 0.42,
    metallic: false,
    localities: ["Oregon", "Madagascar", "India"],
    notes: "Opaque chalcedony pigmented by iron oxides and clays.",
    tests: "Opaque · even color or orbicular · Mohs 7",
    xp: 12,
  },
  {
    id: "carnelian",
    name: "Carnelian",
    formula: "SiO₂",
    system: "trigonal",
    mohs: [6.5, 7],
    sg: [2.6, 2.64],
    streak: "white",
    luster: "waxy",
    diaphaneity: "translucent",
    cleavage: "none",
    magnetism: "none",
    rarity: "common",
    group: "tectosilicate",
    colors: ["orange", "red-orange"],
    hues: [12, 28],
    sat: 0.72,
    val: 0.62,
    metallic: false,
    localities: ["India", "Brazil", "Oregon"],
    notes: "Translucent Fe-stained chalcedony. Warm, even body color.",
    tests: "Translucent orange · not metallic · Mohs 7",
    xp: 16,
  },
  {
    id: "opal",
    name: "Opal",
    formula: "SiO₂·nH₂O",
    system: "amorphous",
    mohs: [5.5, 6.5],
    sg: [1.9, 2.3],
    streak: "white",
    luster: "vitreous",
    diaphaneity: "translucent",
    cleavage: "none",
    magnetism: "none",
    rarity: "rare",
    group: "mineraloid",
    colors: ["play-of-color", "white", "black"],
    hues: [200, 280, 40],
    sat: 0.45,
    val: 0.7,
    metallic: false,
    localities: ["Virgin Valley NV", "Australia", "Ethiopia"],
    notes: "Amorphous silica spheres diffract light. Soft, heat-sensitive, can craze.",
    tests: "Play-of-color · Mohs ~6 · lighter than quartz",
    xp: 48,
  },
  {
    id: "calcite",
    name: "Calcite",
    formula: "CaCO₃",
    system: "trigonal",
    mohs: [3, 3],
    sg: [2.71, 2.71],
    streak: "white",
    luster: "vitreous",
    diaphaneity: "transparent to translucent",
    cleavage: "perfect rhombohedral (3)",
    magnetism: "none",
    rarity: "common",
    group: "carbonate",
    colors: ["colorless", "white", "honey"],
    hues: [40, 50],
    sat: 0.12,
    val: 0.9,
    metallic: false,
    localities: ["Elmwood TN", "Keokuk IA", "Iceland"],
    notes: "Acid fizz is diagnostic. Three perfect cleavages at 75°. Double refraction in Iceland spar.",
    tests: "Mohs 3 · fizzes in dilute HCl · rhombohedral cleavage",
    xp: 10,
  },
  {
    id: "dolomite",
    name: "Dolomite",
    formula: "CaMg(CO₃)₂",
    system: "trigonal",
    mohs: [3.5, 4],
    sg: [2.85, 2.93],
    streak: "white",
    luster: "vitreous",
    diaphaneity: "translucent",
    cleavage: "perfect rhombohedral",
    magnetism: "none",
    rarity: "common",
    group: "carbonate",
    colors: ["white", "pink", "buff"],
    hues: [350, 20],
    sat: 0.15,
    val: 0.82,
    metallic: false,
    localities: ["Herkimer NY", "Missouri", "Italian Alps"],
    notes: "Powdered fizz only. Often saddle-shaped crystals. Host of Herkimer quartz.",
    tests: "Weak acid unless powdered · Mohs 3.5–4",
    xp: 10,
  },
  {
    id: "fluorite",
    name: "Fluorite",
    formula: "CaF₂",
    system: "cubic",
    mohs: [4, 4],
    sg: [3.18, 3.18],
    streak: "white",
    luster: "vitreous",
    diaphaneity: "transparent",
    cleavage: "perfect octahedral (4)",
    magnetism: "none",
    rarity: "common",
    group: "halide",
    colors: ["purple", "green", "blue", "yellow"],
    hues: [275, 140, 210],
    sat: 0.5,
    val: 0.65,
    metallic: false,
    localities: ["Cave-in-Rock IL", "Rogerley UK", "China"],
    notes: "Octahedral cleavage, cubic crystals, often fluorescent. Illinois heritage stone.",
    tests: "Mohs 4 · 4 cleavage directions · often UV fluorescent",
    xp: 20,
  },
  {
    id: "gypsum",
    name: "Gypsum",
    formula: "CaSO₄·2H₂O",
    system: "monoclinic",
    mohs: [2, 2],
    sg: [2.3, 2.3],
    streak: "white",
    luster: "pearly",
    diaphaneity: "transparent",
    cleavage: "perfect (1)",
    magnetism: "none",
    rarity: "common",
    group: "sulfate",
    colors: ["colorless", "white"],
    hues: [0],
    sat: 0.05,
    val: 0.95,
    metallic: false,
    localities: ["Naica MX", "White Sands NM", "Pernatty"],
    notes: "Fingernail scratches it. Selenite, satin spar, alabaster are varieties.",
    tests: "Mohs 2 · flexible thin plates · pearly cleavage",
    xp: 8,
  },
  {
    id: "barite",
    name: "Barite",
    formula: "BaSO₄",
    system: "orthorhombic",
    mohs: [3, 3.5],
    sg: [4.5, 4.5],
    streak: "white",
    luster: "vitreous",
    diaphaneity: "transparent to opaque",
    cleavage: "perfect (1)",
    magnetism: "none",
    rarity: "common",
    group: "sulfate",
    colors: ["white", "honey", "blue"],
    hues: [45, 210],
    sat: 0.2,
    val: 0.8,
    metallic: false,
    localities: ["Elk Creek SD", "Stoneham CO", "Cumbria"],
    notes: "Surprisingly heavy for a non-metallic. SG 4.5 is the pocket scale tell.",
    tests: "High heft · Mohs 3–3.5 · not magnetic",
    xp: 14,
  },
  {
    id: "halite",
    name: "Halite",
    formula: "NaCl",
    system: "cubic",
    mohs: [2, 2.5],
    sg: [2.17, 2.17],
    streak: "white",
    luster: "vitreous",
    diaphaneity: "transparent",
    cleavage: "perfect cubic (3)",
    magnetism: "none",
    rarity: "common",
    group: "halide",
    colors: ["colorless", "orange", "blue"],
    hues: [0, 25],
    sat: 0.1,
    val: 0.92,
    metallic: false,
    localities: ["Wieliczka", "Searles Lake CA", "Salton Sea"],
    notes: "Tastes of salt. Cubic cleavage. Water-soluble — do not leave in rain.",
    tests: "Taste · cubic cleavage · soluble",
    xp: 8,
  },
  {
    id: "pyrite",
    name: "Pyrite",
    formula: "FeS₂",
    system: "cubic",
    mohs: [6, 6.5],
    sg: [5.0, 5.0],
    streak: "greenish-black",
    luster: "metallic",
    diaphaneity: "opaque",
    cleavage: "poor · conchoidal",
    magnetism: "none",
    rarity: "common",
    group: "sulfide",
    colors: ["brass-yellow"],
    hues: [48, 56],
    sat: 0.7,
    val: 0.72,
    metallic: true,
    localities: ["Navajún ES", "Leadville CO", "Illinois"],
    notes: "Fool's gold. Cubes, striated faces, green-black streak. Harder than gold, not sectile.",
    tests: "Green-black streak · Mohs 6–6.5 · cubes · not sectile",
    xp: 16,
  },
  {
    id: "galena",
    name: "Galena",
    formula: "PbS",
    system: "cubic",
    mohs: [2.5, 2.5],
    sg: [7.4, 7.6],
    streak: "lead-gray",
    luster: "metallic",
    diaphaneity: "opaque",
    cleavage: "perfect cubic (3)",
    magnetism: "none",
    rarity: "common",
    group: "sulfide",
    colors: ["lead-gray"],
    hues: [220],
    sat: 0.05,
    val: 0.35,
    metallic: true,
    localities: ["Tri-State MO-KS-OK", "Coeur d'Alene ID", "Broken Hill"],
    notes: "Very dense. Perfect cubic cleavage. Primary ore of lead. Fresh faces are mirror-bright.",
    tests: "Extreme heft · cubic cleavage · lead-gray streak",
    xp: 18,
  },
  {
    id: "sphalerite",
    name: "Sphalerite",
    formula: "ZnS",
    system: "cubic",
    mohs: [3.5, 4],
    sg: [3.9, 4.1],
    streak: "pale yellow to brown",
    luster: "resinous",
    diaphaneity: "translucent to opaque",
    cleavage: "perfect dodecahedral",
    magnetism: "none",
    rarity: "common",
    group: "sulfide",
    colors: ["brown", "black", "honey", "red"],
    hues: [28, 40],
    sat: 0.45,
    val: 0.35,
    metallic: false,
    localities: ["Tri-State", "Elmwood TN", "Santander"],
    notes: "Resinous luster, high RI, dodecahedral cleavage. Often with galena and calcite.",
    tests: "Resinous · pale streak · 6 cleavage dirs",
    xp: 18,
  },
  {
    id: "chalcopyrite",
    name: "Chalcopyrite",
    formula: "CuFeS₂",
    system: "tetragonal",
    mohs: [3.5, 4],
    sg: [4.1, 4.3],
    streak: "greenish-black",
    luster: "metallic",
    diaphaneity: "opaque",
    cleavage: "poor",
    magnetism: "none",
    rarity: "common",
    group: "sulfide",
    colors: ["brass", "iridescent"],
    hues: [46, 54],
    sat: 0.68,
    val: 0.62,
    metallic: true,
    localities: ["Butte MT", "Cornwall", "Sudbury"],
    notes: "Deeper yellow than pyrite, softer, tetrahedral. Peacock tarnish common.",
    tests: "Mohs 3.5–4 · greener yellow than pyrite · green-black streak",
    xp: 16,
  },
  {
    id: "bornite",
    name: "Bornite",
    formula: "Cu₅FeS₄",
    system: "orthorhombic",
    mohs: [3, 3],
    sg: [5.0, 5.1],
    streak: "gray-black",
    luster: "metallic",
    diaphaneity: "opaque",
    cleavage: "poor",
    magnetism: "none",
    rarity: "uncommon",
    group: "sulfide",
    colors: ["peacock", "purple", "blue", "copper-red"],
    hues: [280, 210, 20],
    sat: 0.55,
    val: 0.4,
    metallic: true,
    localities: ["Butte MT", "Cornwall", "Namibia"],
    notes: "Peacock ore. Fresh fracture is copper-red, tarnishes to purple-blue iridescence.",
    tests: "Iridescent tarnish · Mohs 3 · gray-black streak",
    xp: 22,
  },
  {
    id: "malachite",
    name: "Malachite",
    formula: "Cu₂CO₃(OH)₂",
    system: "monoclinic",
    mohs: [3.5, 4],
    sg: [3.6, 4.0],
    streak: "light green",
    luster: "silky",
    diaphaneity: "opaque",
    cleavage: "perfect (1)",
    magnetism: "none",
    rarity: "uncommon",
    group: "carbonate",
    colors: ["green", "banded green"],
    hues: [140, 155],
    sat: 0.72,
    val: 0.48,
    metallic: false,
    localities: ["Bisbee AZ", "Katanga", "Morenci AZ"],
    notes: "Banded green copper carbonate. Fizzes. Often with azurite. Light green streak.",
    tests: "Green streak · acid fizz · Mohs 3.5–4",
    xp: 24,
  },
  {
    id: "azurite",
    name: "Azurite",
    formula: "Cu₃(CO₃)₂(OH)₂",
    system: "monoclinic",
    mohs: [3.5, 4],
    sg: [3.77, 3.77],
    streak: "blue",
    luster: "vitreous",
    diaphaneity: "translucent",
    cleavage: "perfect (1)",
    magnetism: "none",
    rarity: "uncommon",
    group: "carbonate",
    colors: ["deep blue"],
    hues: [220, 235],
    sat: 0.78,
    val: 0.42,
    metallic: false,
    localities: ["Bisbee AZ", "Touissit", "Liufengshan"],
    notes: "Deep azure. Alters to malachite. Fizzes. Blue streak is diagnostic versus sodalite.",
    tests: "Blue streak · acid fizz · Mohs 3.5–4",
    xp: 26,
  },
  {
    id: "copper",
    name: "Native Copper",
    formula: "Cu",
    system: "cubic",
    mohs: [2.5, 3],
    sg: [8.9, 8.9],
    streak: "copper-red",
    luster: "metallic",
    diaphaneity: "opaque",
    cleavage: "none · hackly",
    magnetism: "none",
    rarity: "uncommon",
    group: "native",
    colors: ["copper-red"],
    hues: [18, 28],
    sat: 0.72,
    val: 0.55,
    metallic: true,
    localities: ["Keweenaw MI", "Bisbee AZ", "Michigan UP"],
    notes: "Hackly fracture, sectile, extreme heft. Keweenaw is the type locality for float copper.",
    tests: "Sectile · hackly · copper streak · SG 8.9",
    xp: 36,
  },
  {
    id: "hematite",
    name: "Hematite",
    formula: "Fe₂O₃",
    system: "trigonal",
    mohs: [5, 6],
    sg: [5.3, 5.3],
    streak: "cherry-red",
    luster: "metallic",
    diaphaneity: "opaque",
    cleavage: "none",
    magnetism: "none",
    rarity: "common",
    group: "oxide",
    colors: ["steel-gray", "red-brown", "black"],
    hues: [0, 12],
    sat: 0.35,
    val: 0.28,
    metallic: true,
    localities: ["Lake Superior iron ranges", "Elba", "Graves Mountain GA"],
    notes: "Cherry-red streak is the field diagnostic, even when the specimen looks steel-black.",
    tests: "Cherry-red streak · not magnetic (vs magnetite)",
    xp: 14,
  },
  {
    id: "magnetite",
    name: "Magnetite",
    formula: "Fe₃O₄",
    system: "cubic",
    mohs: [5.5, 6.5],
    sg: [5.2, 5.2],
    streak: "black",
    luster: "metallic",
    diaphaneity: "opaque",
    cleavage: "none",
    magnetism: "strong",
    rarity: "common",
    group: "oxide",
    colors: ["black"],
    hues: [0],
    sat: 0.05,
    val: 0.12,
    metallic: true,
    localities: ["Adirondacks NY", "Kiruna", "Utah", "Magnet Cove AR"],
    notes: "Strongly magnetic. Octahedra common. Black streak versus hematite's red.",
    tests: "Picks up a magnet · black streak · octahedra",
    xp: 16,
  },
  {
    id: "garnet",
    name: "Almandine Garnet",
    formula: "Fe₃Al₂(SiO₄)₃",
    system: "cubic",
    mohs: [7, 7.5],
    sg: [4.1, 4.3],
    streak: "white",
    luster: "vitreous",
    diaphaneity: "transparent to translucent",
    cleavage: "none",
    magnetism: "none",
    rarity: "common",
    group: "nesosilicate",
    colors: ["wine-red", "brown-red"],
    hues: [0, 8],
    sat: 0.68,
    val: 0.38,
    metallic: false,
    localities: ["Wrangell AK", "Connecticut", "India"],
    notes: "Dodecahedra / trapezohedra. No cleavage. Harder than quartz. Common in mica schist.",
    tests: "Isotropic isometric crystals · Mohs 7–7.5 · no cleavage",
    xp: 18,
  },
  {
    id: "beryl",
    name: "Beryl",
    formula: "Be₃Al₂Si₆O₁₈",
    system: "hexagonal",
    mohs: [7.5, 8],
    sg: [2.6, 2.9],
    streak: "white",
    luster: "vitreous",
    diaphaneity: "transparent to translucent",
    cleavage: "poor basal",
    magnetism: "none",
    rarity: "uncommon",
    group: "cyclosilicate",
    colors: ["green", "blue", "colorless", "yellow"],
    hues: [140, 200],
    sat: 0.4,
    val: 0.7,
    metallic: false,
    localities: ["Hiddenite NC", "New England pegmatites", "Brazil"],
    notes: "Hexagonal prisms. Harder than quartz. Varieties: emerald, aquamarine, morganite, heliodor.",
    tests: "Mohs 7.5–8 · hexagonal prism · poor cleavage",
    xp: 28,
  },
  {
    id: "emerald",
    name: "Emerald",
    formula: "Be₃Al₂Si₆O₁₈",
    system: "hexagonal",
    mohs: [7.5, 8],
    sg: [2.7, 2.8],
    streak: "white",
    luster: "vitreous",
    diaphaneity: "transparent",
    cleavage: "poor",
    magnetism: "none",
    rarity: "legendary",
    group: "cyclosilicate",
    colors: ["green"],
    hues: [140, 150],
    sat: 0.7,
    val: 0.42,
    metallic: false,
    localities: ["Hiddenite NC", "Muzo CO", "Zambia"],
    notes: "Cr-V beryl. Garden inclusions typical. US public prospecting at Emerald Hollow.",
    tests: "Mohs 7.5–8 · garden inclusions · hexagonal",
    xp: 64,
  },
  {
    id: "aquamarine",
    name: "Aquamarine",
    formula: "Be₃Al₂Si₆O₁₈",
    system: "hexagonal",
    mohs: [7.5, 8],
    sg: [2.68, 2.74],
    streak: "white",
    luster: "vitreous",
    diaphaneity: "transparent",
    cleavage: "poor",
    magnetism: "none",
    rarity: "rare",
    group: "cyclosilicate",
    colors: ["blue", "blue-green"],
    hues: [190, 205],
    sat: 0.45,
    val: 0.72,
    metallic: false,
    localities: ["Mt. Antero CO", "Brazil", "Pakistan"],
    notes: "Fe²⁺ beryl. High-alpine miarolitic granite in Colorado.",
    tests: "Mohs 7.5–8 · pale blue hexagonal prism",
    xp: 48,
  },
  {
    id: "tourmaline",
    name: "Schorl Tourmaline",
    formula: "NaFe₃Al₆(BO₃)₃Si₆O₁₈(OH)₄",
    system: "trigonal",
    mohs: [7, 7.5],
    sg: [3.0, 3.2],
    streak: "white to gray",
    luster: "vitreous",
    diaphaneity: "opaque to translucent",
    cleavage: "poor",
    magnetism: "none",
    rarity: "common",
    group: "cyclosilicate",
    colors: ["black"],
    hues: [0],
    sat: 0.08,
    val: 0.1,
    metallic: false,
    localities: ["New England", "Pala CA", "Minas Gerais"],
    notes: "Striated trigonal prisms, rounded triangle cross-section. Common black schorl in granite.",
    tests: "Striated prism · triangular cross-section · Mohs 7+",
    xp: 16,
  },
  {
    id: "topaz",
    name: "Topaz",
    formula: "Al₂SiO₄(F,OH)₂",
    system: "orthorhombic",
    mohs: [8, 8],
    sg: [3.5, 3.6],
    streak: "white",
    luster: "vitreous",
    diaphaneity: "transparent",
    cleavage: "perfect basal",
    magnetism: "none",
    rarity: "uncommon",
    group: "nesosilicate",
    colors: ["colorless", "sherry", "blue"],
    hues: [38, 210],
    sat: 0.4,
    val: 0.82,
    metallic: false,
    localities: ["Topaz Mountain UT", "Pikes Peak CO", "Brazil"],
    notes: "Perfect basal cleavage — do not drop. Mohs 8. Thomas Range sherry crystals weather free of rhyolite.",
    tests: "Mohs 8 · basal cleavage · orthorhombic prism",
    xp: 34,
  },
  {
    id: "olivine",
    name: "Olivine (Peridot)",
    formula: "(Mg,Fe)₂SiO₄",
    system: "orthorhombic",
    mohs: [6.5, 7],
    sg: [3.2, 4.4],
    streak: "white",
    luster: "vitreous",
    diaphaneity: "transparent",
    cleavage: "poor",
    magnetism: "none",
    rarity: "uncommon",
    group: "nesosilicate",
    colors: ["olive", "yellow-green"],
    hues: [80, 100],
    sat: 0.58,
    val: 0.55,
    metallic: false,
    localities: ["San Carlos AZ", "Hawaii", "Zabargad"],
    notes: "Mantle xenoliths and basalt. Distinctive olive. Peridot is gem forsterite.",
    tests: "Olive-green · granular in basalt · Mohs 6.5–7",
    xp: 22,
  },
  {
    id: "orthoclase",
    name: "Orthoclase",
    formula: "KAlSi₃O₈",
    system: "monoclinic",
    mohs: [6, 6],
    sg: [2.55, 2.63],
    streak: "white",
    luster: "vitreous",
    diaphaneity: "translucent",
    cleavage: "perfect (2) at 90°",
    magnetism: "none",
    rarity: "common",
    group: "tectosilicate",
    colors: ["flesh-pink", "white", "cream"],
    hues: [18, 30],
    sat: 0.28,
    val: 0.72,
    metallic: false,
    localities: ["granites worldwide", "Madagascar"],
    notes: "K-feldspar. Two cleavages at 90°. Flesh-pink in granite. Mohs 6 — does not scratch glass easily.",
    tests: "Mohs 6 · 90° cleavage · not quartz",
    xp: 10,
  },
  {
    id: "labradorite",
    name: "Labradorite",
    formula: "(Ca,Na)(Al,Si)₄O₈",
    system: "triclinic",
    mohs: [6, 6.5],
    sg: [2.68, 2.72],
    streak: "white",
    luster: "vitreous",
    diaphaneity: "translucent",
    cleavage: "perfect (2)",
    magnetism: "none",
    rarity: "uncommon",
    group: "tectosilicate",
    colors: ["gray", "labradorescence"],
    hues: [200, 140, 40],
    sat: 0.3,
    val: 0.45,
    metallic: false,
    localities: ["Labrador", "Oregon (sunstone)", "Finland"],
    notes: "Schiller from lamellar twinning. Oregon sunstone is a copper-bearing labradorite.",
    tests: "Play of blue/gold on gray feldspar · Mohs 6",
    xp: 24,
  },
  {
    id: "amazonite",
    name: "Amazonite",
    formula: "KAlSi₃O₈",
    system: "triclinic",
    mohs: [6, 6.5],
    sg: [2.56, 2.58],
    streak: "white",
    luster: "vitreous",
    diaphaneity: "translucent",
    cleavage: "perfect (2)",
    magnetism: "none",
    rarity: "uncommon",
    group: "tectosilicate",
    colors: ["green", "blue-green"],
    hues: [155, 175],
    sat: 0.42,
    val: 0.62,
    metallic: false,
    localities: ["Pikes Peak CO", "Amelia VA", "Russia"],
    notes: "Pb-colored microcline. Blocky cleavage, often with smoky quartz.",
    tests: "Mohs 6 · green feldspar cleavage · not jade",
    xp: 22,
  },
  {
    id: "sunstone",
    name: "Oregon Sunstone",
    formula: "(Ca,Na)(Al,Si)₄O₈",
    system: "triclinic",
    mohs: [6, 6.5],
    sg: [2.69, 2.72],
    streak: "white",
    luster: "vitreous",
    diaphaneity: "transparent",
    cleavage: "perfect (2)",
    magnetism: "none",
    rarity: "uncommon",
    group: "tectosilicate",
    colors: ["champagne", "salmon", "copper schiller"],
    hues: [18, 32],
    sat: 0.48,
    val: 0.75,
    metallic: false,
    localities: ["Plush OR", "Lake County OR"],
    notes: "Copper platelets give aventurescence. BLM public collecting area near Plush.",
    tests: "Copper flash in pale feldspar · Mohs 6",
    xp: 30,
  },
  {
    id: "kyanite",
    name: "Kyanite",
    formula: "Al₂SiO₅",
    system: "triclinic",
    mohs: [4.5, 7],
    sg: [3.55, 3.7],
    streak: "white",
    luster: "vitreous",
    diaphaneity: "translucent",
    cleavage: "perfect (1)",
    magnetism: "none",
    rarity: "uncommon",
    group: "nesosilicate",
    colors: ["blue", "gray-blue"],
    hues: [210, 225],
    sat: 0.45,
    val: 0.55,
    metallic: false,
    localities: ["North Carolina", "Brazil", "Kenya"],
    notes: "Anisotropic hardness: ~4.5 along the blade, ~7 across. Diagnostic.",
    tests: "Blade · hardness 4.5 vs 7 by direction",
    xp: 20,
  },
  {
    id: "staurolite",
    name: "Staurolite",
    formula: "Fe₂Al₉Si₄O₂₃(OH)",
    system: "monoclinic",
    mohs: [7, 7.5],
    sg: [3.7, 3.8],
    streak: "white to gray",
    luster: "resinous",
    diaphaneity: "translucent to opaque",
    cleavage: "poor",
    magnetism: "none",
    rarity: "uncommon",
    group: "nesosilicate",
    colors: ["brown", "red-brown"],
    hues: [22, 32],
    sat: 0.5,
    val: 0.32,
    metallic: false,
    localities: ["Georgia", "Virginia", "New Mexico"],
    notes: "Fairy crosses — 60° and 90° twins. Metamorphic schist index mineral.",
    tests: "Cross twins · Mohs 7 · brown",
    xp: 20,
  },
  {
    id: "turquoise",
    name: "Turquoise",
    formula: "CuAl₆(PO₄)₄(OH)₈·4H₂O",
    system: "triclinic",
    mohs: [5, 6],
    sg: [2.6, 2.9],
    streak: "white to greenish",
    luster: "waxy",
    diaphaneity: "opaque",
    cleavage: "perfect but rarely seen",
    magnetism: "none",
    rarity: "uncommon",
    group: "phosphate",
    colors: ["sky-blue", "green-blue"],
    hues: [175, 195],
    sat: 0.55,
    val: 0.62,
    metallic: false,
    localities: ["Sleeping Beauty AZ", "Nevada", "Iran"],
    notes: "Waxy, opaque, Mohs 5–6. Matrix webbing common. Softer than chrysocolla-stained quartz.",
    tests: "Mohs 5–6 · waxy · not glass-hard",
    xp: 28,
  },
  {
    id: "sodalite",
    name: "Sodalite",
    formula: "Na₈Al₆Si₆O₂₄Cl₂",
    system: "cubic",
    mohs: [5.5, 6],
    sg: [2.2, 2.3],
    streak: "white",
    luster: "vitreous",
    diaphaneity: "translucent",
    cleavage: "poor",
    magnetism: "none",
    rarity: "uncommon",
    group: "tectosilicate",
    colors: ["blue", "white veined"],
    hues: [225, 240],
    sat: 0.6,
    val: 0.48,
    metallic: false,
    localities: ["Bancroft ON", "Namibia", "Michigan UP (yooperlite)"],
    notes: "Royal blue, white veins. Yooperlite is fluorescent sodalite syenite.",
    tests: "White streak (vs azurite) · Mohs 5.5–6 · no fizz",
    xp: 22,
  },
  {
    id: "yooperlite",
    name: "Yooperlite",
    formula: "sodalite syenite",
    system: "cubic",
    mohs: [5.5, 6],
    sg: [2.3, 2.5],
    streak: "white",
    luster: "dull",
    diaphaneity: "opaque",
    cleavage: "none",
    magnetism: "none",
    rarity: "uncommon",
    group: "rock",
    colors: ["gray", "fluorescent orange"],
    hues: [220, 30],
    sat: 0.15,
    val: 0.4,
    metallic: false,
    localities: ["Crisp Point MI", "Lake Superior beaches"],
    notes: "Glacial syenite with sodalite that fluoresces orange under 365 nm UV. Night hunt.",
    tests: "365 nm UV orange glow · otherwise drab gray",
    xp: 34,
  },
  {
    id: "obsidian",
    name: "Obsidian",
    formula: "volcanic glass",
    system: "amorphous",
    mohs: [5, 5.5],
    sg: [2.3, 2.6],
    streak: "white",
    luster: "vitreous",
    diaphaneity: "translucent on edges",
    cleavage: "none · conchoidal",
    magnetism: "none",
    rarity: "common",
    group: "mineraloid",
    colors: ["black", "mahogany", "rainbow"],
    hues: [0],
    sat: 0.05,
    val: 0.08,
    metallic: false,
    localities: ["Glass Buttes OR", "Obsidian Cliff WY (protected)", "California"],
    notes: "Rhyolitic glass. Razor conchoidal fracture. Softer than quartz. Rainbow and fire varieties at Glass Buttes.",
    tests: "Mohs 5–5.5 · glass · conchoidal · not magnetic",
    xp: 14,
  },
  {
    id: "nephrite",
    name: "Nephrite Jade",
    formula: "Ca₂(Mg,Fe)₅Si₈O₂₂(OH)₂",
    system: "monoclinic",
    mohs: [6, 6.5],
    sg: [2.9, 3.1],
    streak: "white",
    luster: "greasy",
    diaphaneity: "translucent",
    cleavage: "none · splintery",
    magnetism: "none",
    rarity: "uncommon",
    group: "inosilicate",
    colors: ["green", "white", "black"],
    hues: [130, 150],
    sat: 0.4,
    val: 0.42,
    metallic: false,
    localities: ["Jade Cove CA", "Wyoming", "British Columbia"],
    notes: "Felted amphibole. Tough, greasy, splintery. Jade Cove is collect-with-care shoreline.",
    tests: "Tough · greasy · splintery · Mohs 6–6.5",
    xp: 30,
  },
  {
    id: "rhodochrosite",
    name: "Rhodochrosite",
    formula: "MnCO₃",
    system: "trigonal",
    mohs: [3.5, 4],
    sg: [3.5, 3.7],
    streak: "white",
    luster: "vitreous",
    diaphaneity: "translucent",
    cleavage: "perfect rhombohedral",
    magnetism: "none",
    rarity: "rare",
    group: "carbonate",
    colors: ["pink", "rose", "banded"],
    hues: [340, 352],
    sat: 0.55,
    val: 0.68,
    metallic: false,
    localities: ["Sweet Home CO", "Capillitas AR", "South Africa"],
    notes: "Mn carbonate. Fizzes. Rhombohedral. Banded stalactitic vs gem rhombs from Sweet Home.",
    tests: "Acid fizz · Mohs 3.5–4 · rose · rhombohedral",
    xp: 42,
  },
  {
    id: "wulfenite",
    name: "Wulfenite",
    formula: "PbMoO₄",
    system: "tetragonal",
    mohs: [2.5, 3],
    sg: [6.5, 7.0],
    streak: "white",
    luster: "resinous",
    diaphaneity: "transparent",
    cleavage: "distinct (1)",
    magnetism: "none",
    rarity: "rare",
    group: "molybdate",
    colors: ["orange", "yellow"],
    hues: [28, 42],
    sat: 0.82,
    val: 0.7,
    metallic: false,
    localities: ["Red Cloud AZ", "Los Lamentos MX", "Tsumeb"],
    notes: "Thin tetragonal plates, high heft. Fragile. Classic Arizona desert mineral.",
    tests: "Thin orange plates · heavy · Mohs 3",
    xp: 44,
  },
  {
    id: "diamond",
    name: "Diamond",
    formula: "C",
    system: "cubic",
    mohs: [10, 10],
    sg: [3.5, 3.53],
    streak: "none",
    luster: "adamantine",
    diaphaneity: "transparent",
    cleavage: "perfect octahedral",
    magnetism: "none",
    rarity: "legendary",
    group: "native",
    colors: ["colorless", "yellow", "brown", "white"],
    hues: [0, 50],
    sat: 0.08,
    val: 0.95,
    metallic: false,
    localities: ["Crater of Diamonds AR", "Kimberley", "Yakutia"],
    notes: "Only public diamond pipe in the world you can hunt: Murfreesboro lamproite. Adamantine, greasy on crystals, octahedra.",
    tests: "Mohs 10 · adamantine · greasy crystal faces · sinks in SG 3.3",
    xp: 80,
  },
  {
    id: "petoskey",
    name: "Petoskey Stone",
    formula: "Calcite (Hexagonaria percarinata)",
    system: "trigonal",
    mohs: [3, 4],
    sg: [2.6, 2.7],
    streak: "white",
    luster: "dull",
    diaphaneity: "opaque",
    cleavage: "none (fossil)",
    magnetism: "none",
    rarity: "uncommon",
    group: "fossil",
    colors: ["gray", "brown", "starburst"],
    hues: [30, 40],
    sat: 0.18,
    val: 0.55,
    metallic: false,
    localities: ["Petoskey State Park MI", "Little Traverse Bay"],
    notes: "Devonian colonial coral. Pattern pops when wet. Michigan 25 lb/year limit. Surface gathering.",
    tests: "Hexagonal coral pattern wet · Mohs 3–4 · fizzes",
    xp: 26,
  },
  {
    id: "herkimer",
    name: "Herkimer Diamond",
    formula: "SiO₂",
    system: "trigonal",
    mohs: [7, 7],
    sg: [2.65, 2.65],
    streak: "white",
    luster: "vitreous",
    diaphaneity: "transparent",
    cleavage: "none",
    magnetism: "none",
    rarity: "uncommon",
    group: "tectosilicate",
    colors: ["colorless"],
    hues: [0],
    sat: 0.04,
    val: 0.96,
    metallic: false,
    localities: ["Middleville NY", "Herkimer County NY"],
    notes: "Doubly terminated quartz in Cambrian Little Falls dolostone. Not diamond. Anthraxolite inclusions common.",
    tests: "Double termination · Mohs 7 · in dolostone vugs",
    xp: 28,
  },
  {
    id: "thunderegg",
    name: "Thunderegg",
    formula: "SiO₂ (rhyolite nodule)",
    system: "trigonal",
    mohs: [6.5, 7],
    sg: [2.5, 2.65],
    streak: "white",
    luster: "waxy",
    diaphaneity: "opaque to translucent core",
    cleavage: "none",
    magnetism: "none",
    rarity: "common",
    group: "rock",
    colors: ["gray rind", "banded core"],
    hues: [30, 200, 10],
    sat: 0.25,
    val: 0.5,
    metallic: false,
    localities: ["Rockhound SP NM", "Oregon", "Idaho"],
    notes: "Rhyolite spherulite with chalcedony core. Cut to reveal. Oregon state rock.",
    tests: "Spherical nodule · agate core when cut",
    xp: 18,
  },
  {
    id: "gold",
    name: "Native Gold",
    formula: "Au",
    system: "cubic",
    mohs: [2.5, 3],
    sg: [19.3, 19.3],
    streak: "golden yellow",
    luster: "metallic",
    diaphaneity: "opaque",
    cleavage: "none · hackly",
    magnetism: "none",
    rarity: "legendary",
    group: "native",
    colors: ["gold"],
    hues: [46, 52],
    sat: 0.78,
    val: 0.72,
    metallic: true,
    localities: ["California Mother Lode", "Alaska", "Colorado"],
    notes: "Sectile, never tarnishes, extreme heft. Gold streak. Softer than pyrite. Check claim status before panning.",
    tests: "Sectile · gold streak · SG 19 · not green-black",
    xp: 80,
  },
  {
    id: "corundum",
    name: "Corundum",
    formula: "Al₂O₃",
    system: "trigonal",
    mohs: [9, 9],
    sg: [3.95, 4.1],
    streak: "none",
    luster: "adamantine",
    diaphaneity: "transparent to opaque",
    cleavage: "none · parting",
    magnetism: "none",
    rarity: "rare",
    group: "oxide",
    colors: ["red", "blue", "gray", "brown"],
    hues: [0, 220],
    sat: 0.5,
    val: 0.45,
    metallic: false,
    localities: ["Franklin NC", "Montana Yogo", "Myanmar"],
    notes: "Ruby (Cr) and sapphire. Mohs 9. Barrel crystals, hexagonal. Franklin NC is a classic US locality.",
    tests: "Mohs 9 · barrel hexagonal · adamantine",
    xp: 52,
  },
  {
    id: "apatite",
    name: "Apatite",
    formula: "Ca₅(PO₄)₃(F,Cl,OH)",
    system: "hexagonal",
    mohs: [5, 5],
    sg: [3.1, 3.2],
    streak: "white",
    luster: "vitreous",
    diaphaneity: "transparent to translucent",
    cleavage: "poor",
    magnetism: "none",
    rarity: "common",
    group: "phosphate",
    colors: ["green", "blue", "yellow"],
    hues: [140, 200, 50],
    sat: 0.5,
    val: 0.55,
    metallic: false,
    localities: ["Maine", "Durango MX", "Brazil"],
    notes: "Mohs 5 — scratched by knife. Hexagonal prisms. Often mistaken for beryl (too soft).",
    tests: "Mohs 5 · hexagonal · too soft for beryl/tourmaline",
    xp: 14,
  },
  {
    id: "prehnite",
    name: "Prehnite",
    formula: "Ca₂Al₂Si₃O₁₀(OH)₂",
    system: "orthorhombic",
    mohs: [6, 6.5],
    sg: [2.8, 2.95],
    streak: "white",
    luster: "vitreous",
    diaphaneity: "translucent",
    cleavage: "distinct (1)",
    magnetism: "none",
    rarity: "common",
    group: "inosilicate",
    colors: ["mint-green", "white"],
    hues: [120, 140],
    sat: 0.4,
    val: 0.72,
    metallic: false,
    localities: ["New Jersey Watchungs", "Michigan", "Mali"],
    notes: "Botryoidal mint-green. Trap-rock zeolite associate with datolite and copper.",
    tests: "Botryoidal mint · Mohs 6 · not fluorite",
    xp: 16,
  },
  {
    id: "epidote",
    name: "Epidote",
    formula: "Ca₂Al₂(Fe,Al)(SiO₄)(Si₂O₇)O(OH)",
    system: "monoclinic",
    mohs: [6, 7],
    sg: [3.3, 3.5],
    streak: "white to gray",
    luster: "vitreous",
    diaphaneity: "transparent to opaque",
    cleavage: "perfect (1)",
    magnetism: "none",
    rarity: "common",
    group: "sorosilicate",
    colors: ["pistachio", "dark green"],
    hues: [95, 115],
    sat: 0.5,
    val: 0.35,
    metallic: false,
    localities: ["Prince of Wales AK", "Untersulzbachtal", "California"],
    notes: "Pistachio-green, striated prisms. Common in greenschist and skarn.",
    tests: "Pistachio · striated · Mohs 6–7",
    xp: 14,
  },
  {
    id: "muscovite",
    name: "Muscovite",
    formula: "KAl₂(AlSi₃O₁₀)(OH)₂",
    system: "monoclinic",
    mohs: [2, 2.5],
    sg: [2.76, 2.88],
    streak: "white",
    luster: "pearly",
    diaphaneity: "transparent",
    cleavage: "perfect basal",
    magnetism: "none",
    rarity: "common",
    group: "phyllosilicate",
    colors: ["colorless", "silver"],
    hues: [0],
    sat: 0.05,
    val: 0.9,
    metallic: false,
    localities: ["Pegmatites worldwide", "New England", "India"],
    notes: "Elastic sheets. Perfect cleavage. Light mica versus dark biotite.",
    tests: "Elastic cleavage sheets · Mohs 2–2.5",
    xp: 8,
  },
  {
    id: "vanadinite",
    name: "Vanadinite",
    formula: "Pb₅(VO₄)₃Cl",
    system: "hexagonal",
    mohs: [3, 4],
    sg: [6.6, 7.2],
    streak: "yellowish-white",
    luster: "resinous",
    diaphaneity: "translucent to opaque",
    cleavage: "none",
    magnetism: "none",
    rarity: "rare",
    group: "phosphate",
    colors: ["red", "orange-red"],
    hues: [8, 18],
    sat: 0.82,
    val: 0.48,
    metallic: false,
    localities: ["Mibladen MA", "Apache Mine AZ", "Old Yuma AZ"],
    notes: "Hexagonal barrels, high heft, resinous red. Fragile. Classic Arizona/Morocco.",
    tests: "Red hexagonal barrels · heavy · Mohs 3–4",
    xp: 40,
  },
  {
    id: "celestine",
    name: "Celestine",
    formula: "SrSO₄",
    system: "orthorhombic",
    mohs: [3, 3.5],
    sg: [3.9, 4.0],
    streak: "white",
    luster: "vitreous",
    diaphaneity: "transparent",
    cleavage: "perfect (1)",
    magnetism: "none",
    rarity: "uncommon",
    group: "sulfate",
    colors: ["blue", "white"],
    hues: [205, 220],
    sat: 0.4,
    val: 0.78,
    metallic: false,
    localities: ["Put-in-Bay OH", "Madagascar", "Sicily"],
    notes: "Ice-blue orthorhombic crystals. Ohio islands are classic. Heavier than calcite.",
    tests: "Blue · heavy for a sulfate · Mohs 3–3.5",
    xp: 20,
  },
];

const BY_ID = new Map(MINERALS.map((m) => [m.id, m]));
const BY_NAME = new Map(MINERALS.map((m) => [m.name.toLowerCase(), m]));

export function mineralById(id: string) {
  return BY_ID.get(id);
}

export function mineralByName(name: string) {
  return BY_NAME.get(name.toLowerCase());
}

export function searchMinerals(q: string) {
  const n = q.trim().toLowerCase();
  if (!n) return MINERALS;
  return MINERALS.filter(
    (m) =>
      m.name.toLowerCase().includes(n) ||
      m.formula.toLowerCase().includes(n) ||
      m.group.includes(n) ||
      m.colors.some((c) => c.includes(n)) ||
      m.localities.some((l) => l.toLowerCase().includes(n)),
  );
}

export const TRAY: { mineralId: string; label: string }[] = [
  { mineralId: "amethyst", label: "Violet prism" },
  { mineralId: "pyrite", label: "Brass cube" },
  { mineralId: "malachite", label: "Banded green" },
  { mineralId: "rose-quartz", label: "Massive pink" },
  { mineralId: "hematite", label: "Steel kidney" },
  { mineralId: "fluorite", label: "Octahedron" },
  { mineralId: "copper", label: "Hackly metal" },
  { mineralId: "ls-agate", label: "Fortification" },
];
